# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

repos:
- repo: local
  hooks:
  - id: pytest
    name: pytest
    entry: uv run pytest
    language: system
    types: [python]
    pass_filenames: false
    always_run: true
  - id: ruff-check
    name: ruff check
    entry: uv run ruff check --force-exclude
    language: system
    types: [python]
    require_serial: true
  - id: ruff-format
    name: ruff format
    entry: uv run ruff format --force-exclude
    language: system
    types: [python]
    require_serial: true
